name: SYNC NOTE
on:
  push:
    branches:
      - dev_auto
jobs:
  SYNC_NOTE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev_auto
      - name: Update AUTHORS
        run: |
          git log
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          commit-message: publish note to blog
          title: sync note pull request
          body: $(date +"%Y-%m-%dT%H:%M:%S%z")
          branch: dev_auto
          base: master
