name: SYNC NOTE
on:
  push:
    branches:
      - dev_auto
jobs:
  SYNC_NOTE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev_auto
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: sync note $(date)
          branch: dev_auto
          base: master
